package com.mycompany.escola.view;

import com.mycompany.escola.DAO.AlunoDAO;
import com.mycompany.escola.DAO.ProfessorDAO;
import com.mycompany.escola.model.Aluno;
import com.mycompany.escola.model.Gerenciador;
import com.mycompany.escola.model.Professor;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

public class Tela_adicionar extends javax.swing.JFrame {
    
    private final Gerenciador gerenciador;

    public Tela_adicionar(Gerenciador gerenciador) {
        this.gerenciador = gerenciador;
        initComponents();
        
        jRadioButton_aluno.setSelected(true);
        jTextField_cpf.setVisible(false);
        jLabel_cpf.setVisible(false);
        jTextField_cpf.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_sobrenome = new javax.swing.JTextField();
        jTextField_idade = new javax.swing.JTextField();
        jTextField_cpf = new javax.swing.JTextField();
        jRadioButton_aluno = new javax.swing.JRadioButton();
        jRadioButton_professor = new javax.swing.JRadioButton();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_sobrenome = new javax.swing.JLabel();
        jLabel_idade = new javax.swing.JLabel();
        jLabel_cpf = new javax.swing.JLabel();
        jButton_adicionar = new javax.swing.JButton();
        jLabel_titulo = new javax.swing.JLabel();
        jTextField_turma = new javax.swing.JTextField();
        jLabel_turma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jTextField_sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sobrenomeActionPerformed(evt);
            }
        });

        jTextField_idade.setMinimumSize(new java.awt.Dimension(100, 26));
        jTextField_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idadeActionPerformed(evt);
            }
        });

        jRadioButton_aluno.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_aluno.setText("Aluno");
        jRadioButton_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_alunoActionPerformed(evt);
            }
        });

        jRadioButton_professor.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_professor.setText("Professor");
        jRadioButton_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_professorActionPerformed(evt);
            }
        });

        jLabel_nome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nome.setText("Nome:");

        jLabel_sobrenome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sobrenome.setText("Sobrenome:");

        jLabel_idade.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_idade.setText("Idade:");

        jLabel_cpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cpf.setText("CPF:");

        jButton_adicionar.setBackground(new java.awt.Color(0, 51, 255));
        jButton_adicionar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_adicionar.setText("Adicionar");
        jButton_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adicionarActionPerformed(evt);
            }
        });

        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Cadastro de Alunos ou Professores");

        jTextField_turma.setPreferredSize(new java.awt.Dimension(200, 26));
        jTextField_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_turmaActionPerformed(evt);
            }
        });

        jLabel_turma.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_turma.setText("Turma:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_sobrenome)
                        .addComponent(jLabel_cpf, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel_nome)
                    .addComponent(jLabel_turma)
                    .addComponent(jLabel_idade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_sobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jTextField_nome)
                        .addComponent(jTextField_cpf))
                    .addComponent(jTextField_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_aluno)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_professor))
                    .addComponent(jLabel_titulo))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_adicionar)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_aluno)
                    .addComponent(jRadioButton_professor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sobrenome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_idade)
                    .addComponent(jTextField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_turma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cpf))
                .addGap(18, 18, 18)
                .addComponent(jButton_adicionar)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_alunoActionPerformed
        if (jRadioButton_aluno.isSelected()) {
            jRadioButton_professor.setSelected(false);
            jTextField_cpf.setVisible(false);
            jLabel_cpf.setVisible(false);
            jTextField_cpf.setEnabled(false);
            jLabel_turma.setText("Turma:");
            limparCampos();
        }
    }//GEN-LAST:event_jRadioButton_alunoActionPerformed

    private void jRadioButton_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_professorActionPerformed
        if (jRadioButton_professor.isSelected()) {
            jTextField_cpf.setVisible(true);
            jLabel_cpf.setVisible(true);
            jTextField_cpf.setEnabled(true);
            jRadioButton_aluno.setSelected(false);
            jLabel_turma.setText("Turma/s:");
            limparCampos();
        } 
    }//GEN-LAST:event_jRadioButton_professorActionPerformed

    private void jTextField_sobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sobrenomeActionPerformed
    }//GEN-LAST:event_jTextField_sobrenomeActionPerformed

    private void limparCampos() {
        jTextField_nome.setText("");
        jTextField_sobrenome.setText("");
        jTextField_idade.setText("");
        jTextField_turma.setText("");
        jTextField_cpf.setText("");
    }
    
    private void jButton_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adicionarActionPerformed
        try {
        String nome = jTextField_nome.getText().trim();
        String sobrenome = jTextField_sobrenome.getText().trim();
        String idadeTexto = jTextField_idade.getText().trim();
        String turmaTexto = jTextField_turma.getText().trim().toUpperCase();
        String cpfTexto = jTextField_cpf.getText().trim();

        if (turmaTexto.isEmpty() || nome.isEmpty() || sobrenome.isEmpty() || idadeTexto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Erro: complete todos os campos obrigatórios.");
            return;
        }

        int idade = Integer.parseInt(idadeTexto);
        String opcao = "";

        if (jRadioButton_aluno.isSelected()) {
            opcao = "ALUNO";
        } else if (jRadioButton_professor.isSelected()) {
            opcao = "PROFESSOR";
        }

        switch (opcao) {
            case "ALUNO" -> {
                if (!turmaTexto.equals("A") && !turmaTexto.equals("B") && !turmaTexto.equals("C")) {
                    JOptionPane.showMessageDialog(null, "Erro: insira uma turma válida: A, B ou C.");
                    return;
                }
                
                AlunoDAO alunoDao = new AlunoDAO();
                int matriculaNova = alunoDao.gerarMatriculaUnica();
                
                Aluno aluno = new Aluno(nome, sobrenome, idade, turmaTexto);
                aluno.setMatricula(matriculaNova);
                
                alunoDao.inserir(aluno);

                JOptionPane.showMessageDialog(null, "Aluno adicionado com sucesso!");
            }

            case "PROFESSOR" -> {
                if (cpfTexto.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Erro: o campo CPF está vazio.");
                    return;
                } else if (!cpfTexto.matches("\\d{11}")) {
                    JOptionPane.showMessageDialog(null, "Erro: CPF deve conter exatamente 11 números.");
                    return;
                }
                
                String[] turmas = turmaTexto.split("\\s*,\\s*|\\s+");
                
                //Criação de HashSet para evitar turmas duplicadas
                Set<String> turmaSet = new HashSet<>();

                for (String s : turmas) {
                    if (!s.equals("A") && !s.equals("B") && !s.equals("C") ) {
                        JOptionPane.showMessageDialog(null, "Erro: insira apenas turmas válidas (A, B ou C).");
                        return;
                    }
                    
                    //Se não for verdadeiro da erro, por que HashSet não aceita valores duplicados
                    boolean v = turmaSet.add(s);
                    if (!v) {
                        JOptionPane.showMessageDialog(null, "Erro: a turma '" + s + "' foi inserida mais de uma vez.");
                        return;
                    }
                }

                String turmaFormatada = String.join(", ", turmas);

                Professor prof = new Professor(nome, sobrenome, idade, cpfTexto, turmaFormatada);
                ProfessorDAO profDao = new ProfessorDAO();
                
                profDao.inserir(prof);

                JOptionPane.showMessageDialog(null, "Professor adicionado com sucesso!");
            }

            default -> 
                JOptionPane.showMessageDialog(null, "Por favor, selecione ALUNO ou PROFESSOR.");
        }
        
        limparCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro: idade deve ser um número válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_adicionarActionPerformed

    private void jTextField_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idadeActionPerformed

    private void jTextField_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_turmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_turmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_adicionar;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_idade;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_sobrenome;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_turma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_aluno;
    private javax.swing.JRadioButton jRadioButton_professor;
    private javax.swing.JTextField jTextField_cpf;
    private javax.swing.JTextField jTextField_idade;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_sobrenome;
    private javax.swing.JTextField jTextField_turma;
    // End of variables declaration//GEN-END:variables
}
