package com.mycompany.escola.view;

import com.mycompany.escola.model.Aluno;
import com.mycompany.escola.model.Gerenciador;
import com.mycompany.escola.model.Professor;

public class Tela_adicionar extends javax.swing.JFrame {
    
    private final Gerenciador gerenciador;

    public Tela_adicionar(Gerenciador gerenciador) {
        this.gerenciador = gerenciador;
        initComponents();
        
        jRadioButton_aluno.setSelected(true);
        jTextField_cpf.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_sobrenome = new javax.swing.JTextField();
        jTextField_idade = new javax.swing.JTextField();
        jTextField_cpf = new javax.swing.JTextField();
        jRadioButton_aluno = new javax.swing.JRadioButton();
        jRadioButton_professor = new javax.swing.JRadioButton();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_sobrenome = new javax.swing.JLabel();
        jLabel_idade = new javax.swing.JLabel();
        jLabel_cpf = new javax.swing.JLabel();
        jButton_adicionar = new javax.swing.JButton();
        jLabel_titulo = new javax.swing.JLabel();
        jTextField_turma = new javax.swing.JTextField();
        jLabel_turma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jTextField_sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sobrenomeActionPerformed(evt);
            }
        });

        jRadioButton_aluno.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_aluno.setText("Aluno");
        jRadioButton_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_alunoActionPerformed(evt);
            }
        });

        jRadioButton_professor.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_professor.setText("Professor");
        jRadioButton_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_professorActionPerformed(evt);
            }
        });

        jLabel_nome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nome.setText("Nome:");

        jLabel_sobrenome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sobrenome.setText("Sobrenome:");

        jLabel_idade.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_idade.setText("Idade:");

        jLabel_cpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cpf.setText("CPF:");

        jButton_adicionar.setBackground(new java.awt.Color(0, 51, 255));
        jButton_adicionar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_adicionar.setText("Adicionar");
        jButton_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adicionarActionPerformed(evt);
            }
        });

        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Cadastro de Alunos ou Professores");

        jLabel_turma.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_turma.setText("Turma:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_adicionar)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton_aluno)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_professor))
                            .addComponent(jLabel_titulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel_sobrenome)
                                        .addComponent(jLabel_idade, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_cpf, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel_nome)
                                    .addComponent(jLabel_turma))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_turma)
                                    .addComponent(jTextField_sobrenome)
                                    .addComponent(jTextField_nome)
                                    .addComponent(jTextField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))
                        .addContainerGap(120, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_aluno)
                    .addComponent(jRadioButton_professor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sobrenome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_idade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_turma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_turma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cpf))
                .addGap(33, 33, 33)
                .addComponent(jButton_adicionar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_alunoActionPerformed
        if (jRadioButton_aluno.isSelected()) {
            jRadioButton_professor.setSelected(false);
            jTextField_cpf.setEnabled(false);
            jLabel_turma.setText("Turma");
        }
    }//GEN-LAST:event_jRadioButton_alunoActionPerformed

    private void jRadioButton_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_professorActionPerformed
        if (jRadioButton_professor.isSelected()) {
            jTextField_cpf.setEnabled(true);
            jRadioButton_aluno.setSelected(false);
            jLabel_turma.setText("Turma/s");
        } 
    }//GEN-LAST:event_jRadioButton_professorActionPerformed

    private void jTextField_sobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sobrenomeActionPerformed

    private void limparCampos() {
        jTextField_nome.setText("");
        jTextField_sobrenome.setText("");
        jTextField_idade.setText("");
        jTextField_turma.setText("");
        jTextField_cpf.setText("");
    }
    
    private void jButton_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adicionarActionPerformed
        try {
            String nome = jTextField_nome.getText();
            String sobrenome = jTextField_sobrenome.getText();
            int idade = Integer.parseInt(jTextField_idade.getText());
            String turmaTexto = jTextField_turma.getText().toUpperCase();

            if (turmaTexto.isEmpty() || nome.isEmpty() || sobrenome.isEmpty()) {
                System.out.println("Erro: complete os campos vazios");
                return;
            }

            char turma = turmaTexto.charAt(0);

            String opcao = "";  // para o switch

            if (jRadioButton_aluno.isSelected()) {
                opcao = "ALUNO";
            } else if (jRadioButton_professor.isSelected()) {
                opcao = "PROFESSOR";
            }

            switch (opcao) {
                case "ALUNO" -> {
                    Aluno aluno = new Aluno(nome, sobrenome, idade, turma);
                    
                    if (!turmaTexto.equals("A") && !turmaTexto.equals("B") && !turmaTexto.equals("C")) {
                        System.out.println("Erro: insira uma turma válida: A, B, C.");
                        return;
                    }
                    
                    gerenciador.adicionarPessoa(aluno);
                    gerenciador.listarPessoas();
                    System.out.println("Aluno adicionado com sucesso!");
                    break;
                }

                case "PROFESSOR" -> {
                    String cpfTexto = jTextField_cpf.getText();
                    if (cpfTexto.isEmpty()) {
                        System.out.println("Erro: o campo 'CPF' está vazio.");
                        return;
                    } else if (cpfTexto.length() != 11 || !cpfTexto.matches("\\d{11}")){
                        System.out.println("Erro: digite o CPF com exatamente 11 números.");
                        return;
                    }
                    
                    String cpfFormatado = cpfTexto.substring(0, 9) + "-" + cpfTexto.substring(9);
                    
                    String[] turmas = turmaTexto.split("\\s*,\\s*|\\s+");
                    
                    for (String s : turmas) {
                        if (!s.equals("A") && !s.equals("B") && !s.equals("C")) {
                            System.out.println("Erro: insira apenas turmas válidas: A, B ou C.");
                            return;
                        }
                    }
                    
                    String turmaFormatada = String.join(", ", turmas);

                    Professor prof = new Professor(nome, sobrenome, idade, cpfFormatado, turmaFormatada);
                    gerenciador.adicionarPessoa(prof);
                    gerenciador.listarPessoas();
                    System.out.println("Professor adicionado com sucesso!");
                    break;
                }
            }
            
            limparCampos();

        } catch (NumberFormatException e) {
            System.out.println("Erro ao converter idade: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_adicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_adicionar;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_idade;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_sobrenome;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_turma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_aluno;
    private javax.swing.JRadioButton jRadioButton_professor;
    private javax.swing.JTextField jTextField_cpf;
    private javax.swing.JTextField jTextField_idade;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_sobrenome;
    private javax.swing.JTextField jTextField_turma;
    // End of variables declaration//GEN-END:variables
}
