/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.escola.view;

import com.mycompany.escola.model.Aluno;
import com.mycompany.escola.model.Gerenciador;
import com.mycompany.escola.model.Pessoa;
import com.mycompany.escola.model.Professor;

/**
 *
 * @author Wellington
 */
public class Tela_remover extends javax.swing.JFrame {

    private final Gerenciador gerenciador;
    
    public Tela_remover(Gerenciador gerenciador) {
        this.gerenciador = gerenciador;
        initComponents();
        
        jRadioButton_aluno.setSelected(true);
        jTextField_cpf.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton_aluno = new javax.swing.JRadioButton();
        jRadioButton_professor = new javax.swing.JRadioButton();
        jTextField_matricula = new javax.swing.JTextField();
        jTextField_cpf = new javax.swing.JTextField();
        jLabel_matricula = new javax.swing.JLabel();
        jLabel_cpf = new javax.swing.JLabel();
        jButton_remover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jRadioButton_aluno.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_aluno.setText("Aluno");
        jRadioButton_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_alunoActionPerformed(evt);
            }
        });

        jRadioButton_professor.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_professor.setText("Professor");
        jRadioButton_professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_professorActionPerformed(evt);
            }
        });

        jLabel_matricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_matricula.setText("Matrícula:");

        jLabel_cpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_cpf.setText("CPF:");

        jButton_remover.setBackground(new java.awt.Color(0, 51, 255));
        jButton_remover.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remover.setText("Remover");
        jButton_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removerActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Remover um Aluno ou Professor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_remover)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_matricula)
                            .addComponent(jLabel_cpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton_aluno)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton_professor)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_aluno)
                    .addComponent(jRadioButton_professor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_matricula))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_cpf)
                    .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButton_remover)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_professorActionPerformed
        if (jRadioButton_professor.isSelected()) {
            jTextField_cpf.setEnabled(true);
            jRadioButton_aluno.setSelected(false);
            jTextField_matricula.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton_professorActionPerformed

    private void jRadioButton_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_alunoActionPerformed
        if (jRadioButton_aluno.isSelected()) {
            jTextField_matricula.setEnabled(true);
            jRadioButton_professor.setSelected(false);
            jTextField_cpf.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton_alunoActionPerformed

    private void jButton_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removerActionPerformed
        try {
            String opcao = "";
            
            if (jRadioButton_aluno.isSelected()) {
                opcao = "ALUNO";
            } else if (jRadioButton_professor.isSelected()) {
                opcao = "PROFESSOR";
            }
            
            switch(opcao) {
                case "ALUNO":
                    if(jTextField_matricula.getText().isEmpty()) {
                        System.out.println("Erro: campo matrícula em branco.");
                        return;
                    } else {
                        int matricula = Integer.parseInt(jTextField_matricula.getText());
                    
                        for (Pessoa p: gerenciador.getPessoas()) {
                            if (p instanceof Aluno a) {
                                if (a.getMatricula() == matricula) {
                                    gerenciador.removerPessoa(a);
                                    break;
                                } else {
                                    System.out.println("Aluno não encontrado.");
                                    return;
                                }
                            }
                        }
                    }
                    
                case "PROFESSOR":
                    if(jTextField_cpf.getText().isEmpty()) {
                        System.out.println("Erro: campo cpf em branco.");
                        return;
                    } else {
                        String cpf = jTextField_cpf.getText();
                    
                        for (Pessoa p: gerenciador.getPessoas()) {
                            if(p instanceof Professor prof) {
                                if (prof.getCpf().equals(cpf)) {
                                    gerenciador.removerPessoa(prof);
                                    break;
                                } else {
                                    System.out.println("Professor não encontrado.");
                                    return;
                                }
                            }
                        }
                    }
            }
            
            jTextField_matricula.setText("");
            jTextField_cpf.setText("");
            
        } catch (NumberFormatException e) {
            System.out.println("Erro ao converter matrícula: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_removerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_remover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_matricula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_aluno;
    private javax.swing.JRadioButton jRadioButton_professor;
    private javax.swing.JTextField jTextField_cpf;
    private javax.swing.JTextField jTextField_matricula;
    // End of variables declaration//GEN-END:variables
}
